AWSTemplateFormatVersion: '2010-09-09'
Description: A Slack bot on AWS Lambda with Litestar

Parameters:
  ImageUri:
    Type: String
    Default: 216989105690.dkr.ecr.ap-northeast-2.amazonaws.com/sandbox:latest
    Description: Fully qualified ECR image reference used for both functions (tag or digest)
  SlackBotToken:
    Type: String
    NoEcho: true
    Description: Slack Bot User OAuth Token (resolved from SSM by deploy script)
  SlackSigningSecret:
    Type: String
    NoEcho: true
    Description: Slack Signing Secret (resolved from SSM by deploy script)
  LanggraphCheckpointBackend:
    Type: String
    Default: memory
    AllowedValues:
      - memory
      - postgres
      - dynamodb
    Description: Checkpoint backend for LangGraph runtime
  BigqueryThreadMemoryBackend:
    Type: String
    Default: memory
    AllowedValues:
      - memory
      - dynamodb
    Description: Thread memory backend for analyst agent

Resources:
  WebFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  SlackBgFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  LangGraphCheckpointTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-langgraph-checkpoints"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  AgentThreadMemoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-agent-thread-memory"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  WebFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt WebFunctionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Architectures:
        - arm64
      Timeout: 15
      MemorySize: 1024
      Environment:
        Variables:
          AWS_LWA_PORT: "8080"
          APP_MODE: "web"
          SLACK_BOT_TOKEN: !Ref SlackBotToken
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          SLACK_BG_FUNCTION_NAME: !Ref SlackBgFunction
          LANGGRAPH_CHECKPOINT_BACKEND: !Ref LanggraphCheckpointBackend
          LANGGRAPH_DYNAMODB_TABLE: !Ref LangGraphCheckpointTable
          LANGGRAPH_DYNAMODB_REGION: !Ref AWS::Region
          BIGQUERY_THREAD_MEMORY_BACKEND: !Ref BigqueryThreadMemoryBackend
          BIGQUERY_THREAD_MEMORY_DDB_TABLE: !Ref AgentThreadMemoryTable
          BIGQUERY_CONTEXT_WINDOW_TOKENS: "128000"
          BIGQUERY_CONTEXT_TRIGGER_RATIO: "0.70"
          BIGQUERY_CONTEXT_TARGET_RATIO: "0.50"
          BIGQUERY_CONTEXT_RESERVE_OUTPUT_TOKENS: "4000"
          BIGQUERY_CONTEXT_KEEP_RECENT_TURNS: "8"
          BIGQUERY_CONTEXT_MAX_SUMMARY_CHARS: "4000"
          BIGQUERY_CONTEXT_REBASE_EVERY: "8"
          BIGQUERY_CONTEXT_FAIL_OPEN: "true"

  WebFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref WebFunction
      AuthType: NONE

  WebFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  WebFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebFunction
      Action: lambda:InvokeFunction
      Principal: "*"
      InvokedViaFunctionUrl: true


  SlackBgFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt SlackBgFunctionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Architectures:
        - arm64
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          AWS_LWA_PORT: "8080"
          AWS_LWA_PASS_THROUGH_PATH: "/slack/background"
          APP_MODE: "slack-bg"
          SLACK_BOT_TOKEN: !Ref SlackBotToken
          LANGGRAPH_CHECKPOINT_BACKEND: !Ref LanggraphCheckpointBackend
          LANGGRAPH_DYNAMODB_TABLE: !Ref LangGraphCheckpointTable
          LANGGRAPH_DYNAMODB_REGION: !Ref AWS::Region
          BIGQUERY_THREAD_MEMORY_BACKEND: !Ref BigqueryThreadMemoryBackend
          BIGQUERY_THREAD_MEMORY_DDB_TABLE: !Ref AgentThreadMemoryTable
          BIGQUERY_CONTEXT_WINDOW_TOKENS: "128000"
          BIGQUERY_CONTEXT_TRIGGER_RATIO: "0.70"
          BIGQUERY_CONTEXT_TARGET_RATIO: "0.50"
          BIGQUERY_CONTEXT_RESERVE_OUTPUT_TOKENS: "4000"
          BIGQUERY_CONTEXT_KEEP_RECENT_TURNS: "8"
          BIGQUERY_CONTEXT_MAX_SUMMARY_CHARS: "4000"
          BIGQUERY_CONTEXT_REBASE_EVERY: "8"
          BIGQUERY_CONTEXT_FAIL_OPEN: "true"

Outputs:
  WebFunctionUrl:
    Description: Function URL for the Litestar web endpoint
    Value: !GetAtt WebFunctionUrl.FunctionUrl

  SlackBgFunctionName:
    Description: Name of the Slack background function
    Value: !Ref SlackBgFunction
  SlackEventsUrl:
    Description: URL for Slack Events/Commands webhook
    Value: !Sub "${WebFunctionUrl}slack/events"
