---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest(ingest)
	classify_relevance(classify_relevance)
	classify_intent(classify_intent)
	generate_or_validate(generate_or_validate)
	validate_candidate_sql(validate_candidate_sql)
	policy_gate(policy_gate)
	execute_sql(execute_sql)
	compose_response(compose_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest;
	classify_intent --> generate_or_validate;
	classify_relevance -. &nbsp;stop&nbsp; .-> __end__;
	classify_relevance -. &nbsp;proceed&nbsp; .-> classify_intent;
	execute_sql --> compose_response;
	generate_or_validate --> validate_candidate_sql;
	ingest --> classify_relevance;
	policy_gate -. &nbsp;skip&nbsp; .-> compose_response;
	policy_gate -. &nbsp;execute&nbsp; .-> execute_sql;
	validate_candidate_sql --> policy_gate;
	compose_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
